# Package Overview
package_name: classification_model

# Data Files
raw_data_file: raw.csv
#training_data_file: train.csv
#test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: survived

pipeline_name: classification_model
pipeline_save_file: classification_model_output_v

features:
  - pclass
  - sex
  - age
  - sibsp
  - parch
  - fare
  - cabin
  - embarked
  - title

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

C: 0.001

# categorical variables
categorical_vars:
  - sex
  - embarked
  - title
  - cabin

# numerical variables
numerical_vars:
  - age
  - fare

# cabin variable
cabin:
  - cabin

unused_variables:
  - name
  - ticket
  - boat
  - body
  - home_dest

variables_to_rename:
  home.dest: home_dest